modLoader="javafml" #mandatory
loaderVersion="[26,)" #mandatory (24 is current forge version)
issueTrackerURL="http://my.issue.tracker/" #optional

[[mods]]
	modId="drpmedieval"
	version="${version}"
	displayName="Dark Roleplay Medieval"
	updateJSONURL="https://dark-roleplay.net/files/versions/drpmedieval/drpmedieval-1.13.2.json" #optional
	displayURL="https://dark-roleplay.net/"
	#logoFile="examplemod.png" #optional
	credits="Lead Programmer: JTK222, Jr. Programmer: 0Mr_X0, Artists: Rolfaal & Kanno (https://twitter.com/lKanno_)"
	authors=["JTK222", "0Mr_X0", "Rolfaal", "Kanno"]
	description='''Dark Roleplay Medieval, is... //TODO FINISH THE DESCRIPTION'''

dependencies.drpmedieval = [
    {modid="forge", mandatory=true, versionRange="[28.1,40}", ordering="NONE",side="BOTH"},
    {modid="marg", mandatory=true, versionRange="[1.14.4-0.2.2}", ordering="BEFORE",side="BOTH"}
]


