name: Java CI

on:
  push:
    tags:
      - 'v?\d.*'

jobs:
  build:
    env:
      MVN_REPO: ${{ secrets.mvn_repo }}
      MVN_USER: ${{ secrets.mvn_user }}
      MVN_PASSWORD: ${{ secrets.mvn_password }}
      
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Set env
        run: echo ::set-env name=RELEASE_VERSION::$(echo ${GITHUB_REF:10})
      - name: Set up JDK 1.8
      - uses: actions/setup-java@v1
        with:
          java-version: 1.8
        env:
          MVN_REPO: ${{ secrets.mvn_repo }}
          MVN_USER: ${{ secrets.mvn_username }}
          MVN_PASSWORD: ${{ secrets.mvn_password }}
        
      - name: Build with Gradle
        run: ./gradlew publish
