name: Java CI

on:
  push:
    tags:
      - 'v?\d.*'

jobs:
  build:
    env:
      MVN_REPO: ${{ secrets.mvn_repo }}
      MVN_USER: ${{ secrets.mvn_user }}
      MVN_PASSWORD: ${{ secrets.mvn_password }}
      CURSE_API_KEY: ${{ secrets.CURSE_API_KEY }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Set Release Version
        run: echo ::set-env name=RELEASE_VERSION::$(echo ${GITHUB_REF:10})
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Publish to maven with Gradle
        run: ./gradlew publish
      - name: Publish to curseforge with Gradle
        run: ./gradlew upload
